language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
services: mysql
before_script:
  - mysql -e 'create database generatedata_test;'
script: phpunit --configuration tests/phpunit_config.xml --coverage-text