language: node_js
node_js:
  - 12

install:
  - nvm install 12
  - yarn install

before_script:
  - cp .env.default .env && yarn build

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn build && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
