version: "3"

networks:
  gd-network:
    driver: bridge

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    networks:
      - gd-network
    expose:
      - "${GD_API_SERVER_PORT}"
    ports:
      - "${GD_API_SERVER_PORT}:${GD_API_SERVER_PORT}"
    restart: on-failure
    volumes:
      - .:/home/app/generatedata
      - /home/app/generatedata/node_modules

  db:
    container_name: db
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "${GD_DB_PORT}"
    ports:
      - "${GD_DB_PORT}:${GD_DB_PORT}"
    networks:
      - gd-network
    environment:
      MYSQL_ROOT_PASSWORD: ${GD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${GD_DB_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    volumes:
      - ./server/database/_dbStructure.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./data/db:/var/lib/mysql
