networks:
  gd-network:
    driver: bridge

services:
  server:
    container_name: server
    build:
      context: ../../
      dockerfile: ./apps/server/Dockerfile
    depends_on:
      - db
    networks:
      - gd-network
    expose:
      - "3001"
    ports:
      - "3001:3001"
    restart: on-failure
    volumes:
      - ../../:/home/app/generatedata

  db:
    container_name: db
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - gd-network
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeNow!
      MYSQL_DATABASE: generatedata
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
    volumes:
      - ../../packages/config/_dbStructure.sql:/docker-entrypoint-initdb.d/setup.sql
      - ../../data/db:/var/lib/mysql
